unique_ids:
  assets:
    standard-page.html: EZSIJDDJ6N4QOBJJ76KEWWP2OFW5FY5U
    theme.css: HJZLR47R7AF7RO2DO6IAN4NUXMI7LKTE
  forms:
    Form1: YCH7GDFOOLWEKFO63W77QVX4CF62O37X
  modules: {}
  scripts: {}
  server_modules: {}
